name: alson_education
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  http: ^1.2.2
  url_launcher: ^6.0.0
  file_picker: ^5.0.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.2
  flutter_pdfview: ^1.3.2
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
  
