name: alson_education
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.0
  file_picker: ^5.0.0
  url_launcher: ^6.0.0
  shared_preferences: ^2.0.0
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  flutter_pdfview: ^1.3.0
  cached_network_image: ^3.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png