name: alson_education
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  file_picker: ^8.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
