name: alson_education
description: A new Flutter project.
version: 1.0.0+1

environment:

  sdk: '>=3.2.0 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  flutter_lints: ^3.0.2      # لقواعد التحليل الثابت
  sqflite: ^2.3.3           # قاعدة بيانات SQLite (غير مدعومة على الويب)
  path_provider: ^2.1.4     # لمسارات الملفات (غير مدعومة على الويب)
  file_picker: ^8.1.2       # لرفع الملفات (مدعوم على معظم المنصات)
  path: ^1.9.0             # للتعامل مع المسارات
  intl: ^0.19.0            # لتنسيق التاريخ (متوافق عبر المنصات)
  excel: ^4.0.5            # لقراءة ملفات Excel (متوافق عبر المنصات)
  hive: ^2.2.3             # بديل لـ sqflite على الويب والمنصات الأخرى
  hive_flutter: ^1.1.0      # تكامل Hive مع Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9      # لتوليد كود Hive
  hive_generator: ^2.0.1    # لتوليد كود Hive

flutter:
  uses-material-design: true
  assets:
    - assets/img/           # تأكد من وجود هذا المجلد
