name: alson_education
description: A new Flutter project for Alson Education.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  excel: ^2.0.0
  uuid: ^3.0.7
  intl: ^0.18.0
  url_launcher: ^6.1.10
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  share_plus: ^7.0.0
  google_sign_in: ^6.1.0
  encrypt: ^5.0.1
  flutter_local_notifications: ^17.0.0 # للإشعارات
  flutter_otp_text_field: ^1.1.0 # لـ OTP

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/icon.png
    - assets/img/po.jpg
