
name: alson_education
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.2.1
  file_picker: ^6.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
