name: alson_education
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.3
  file_picker: ^6.1.1
  excel: ^3.0.0
  path_provider: ^2.0.15
  open_file: ^3.3.3
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  image_picker: ^1.1.2
  flutter_email_sender: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png