name: alson_education
description: A new Flutter project for Alson Education.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  path: ^1.8.0
  file_picker: ^4.6.1
  url_launcher: ^6.0.20
  intl: ^0.17.0
  provider: ^6.0.0
  flutter_material_color_picker: ^1.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon.png
    - assets/img/po.jpg