name: alson_education
description: A new Flutter project for Alson Education.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # مكتبات الـ UI والرسوم المتحركة
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0  # لعرض مؤشر التحميل

  # مكتبات إدارة قاعدة البيانات والتخزين
  sqflite: ^2.3.0  # لقاعدة البيانات SQLite
  path_provider: ^2.1.1  # للوصول إلى مسارات التخزين
  flutter_secure_storage: ^8.0.0  # لتخزين البيانات الحساسة بأمان

  # مكتبات التعامل مع الملفات
  file_picker: ^5.5.0  # لاختيار الملفات
  excel: ^2.0.0  # لمعالجة ملفات Excel

  # مكتبات الشبكة والمعرفات
  http: ^0.13.5  # للتعامل مع طلبات HTTP
  uuid: ^3.0.7  # لتوليد معرفات فريدة

  # مكتبات إضافية
  url_launcher: ^6.1.10
  intl: ^0.18.0  # لتنسيق التاريخ والوقت (مستخدم في ChatScreen)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # لتحليل الكود وتحسينه

flutter:
  uses-material-design: true

  # إعداد الأصول (Assets)
  assets:
    - assets/img/icon.png
    - assets/img/po.jpg

  # يمكن إضافة خطوط مخصصة هنا إذا لزم الأمر
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
