name: Build Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          
      - uses: android-actions/setup-android@v2
      
      - run: |
          yes | sdkmanager --install "platforms;android-34"
          yes | sdkmanager --install "build-tools;34.0.0"
          flutter doctor -v
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
