name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"  # إصدار Flutter المدعوم
          channel: stable
          cache: true
          cache-key: flutter-pub-cache

      - name: Precache Flutter
        run: flutter precache --android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --update

      - name: Install Android Tools
        run: |
          yes | sdkmanager --install "platforms;android-34"
          yes | sdkmanager --install "build-tools;34.0.0"
          yes | sdkmanager --install "cmake;3.22.1"
          yes | sdkmanager --install "ndk;25.2.9519653"

      - name: Clean Project
        run: flutter clean

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
          --no-tree-shake-icons \
          --target-platform android-arm,android-arm64,android-x64 \
          --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          if-no-files-found: error
          retention-days: 7

      - name: Show APK Info
        run: |
          ls -la build/app/outputs/flutter-apk/
          file build/app/outputs/flutter-apk/*.apk
