name: Build Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: stable
      
      - run: flutter config --no-analytics
      - run: flutter clean
      
      - uses: android-actions/setup-android@v2
      - run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --install "platforms;android-34"
          yes | sdkmanager --install "build-tools;34.0.0"
      
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
