name: Build Android

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
      - run: flutter create --platforms=android .  # إعادة الإنشاء هنا
      - uses: android-actions/setup-android@v2
      - run: |
          yes | sdkmanager --install "platforms;android-34"
          yes | sdkmanager --install "build-tools;34.0.0"
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

