name: Build Flutter for All Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: zip -r android-apk.zip build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Android APK
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'android-apk.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'android-apk',
              path: path,
              run_id: context.runId
            });

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: zip -r ios-app.zip build/ios/iphoneos/Runner.app
      - name: Upload iOS App
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'ios-app.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'ios-app',
              path: path,
              run_id: context.runId
            });

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - run: zip -r web-app.zip build/web
      - name: Upload Web App
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'web-app.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'web-app',
              path: path,
              run_id: context.runId
            });

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: powershell -Command "Compress-Archive -Path build/windows/runner/Release -DestinationPath windows-app.zip"
      - name: Upload Windows App
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'windows-app.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'windows-app',
              path: path,
              run_id: context.runId
            });

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - run: zip -r macos-app.zip build/macos/Build/Products/Release
      - name: Upload macOS App
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'macos-app.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'macos-app',
              path: path,
              run_id: context.runId
            });

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - run: zip -r linux-app.zip build/linux/x64/release/bundle
      - name: Upload Linux App
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = 'linux-app.zip';
            await github.rest.actions.uploadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'linux-app',
              path: path,
              run_id: context.runId
            });
